# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: my-OpenWrt-CI

on:
  schedule:
    - cron: 0 20 */7 * *
  push:
    branches:
      - master

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
      - name: add app
        run: |
          cd package/lean/
          rm -rf luci-theme-argon
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
          git clone --depth=1 https://github.com/jerrykuku/lua-maxminddb.git
          git clone --depth=1 https://github.com/jerrykuku/luci-app-vssr.git
          cd ../
          git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall.git
      - name: Update feeds
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_LIBMBEDTLS_HAVE_SSE2=y
          CONFIG_LIBSODIUM_MINIMAL=y
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_boost=y
          CONFIG_PACKAGE_boost-date_time=y
          CONFIG_PACKAGE_boost-program_options=y
          CONFIG_PACKAGE_boost-system=y
          CONFIG_PACKAGE_coreutils=y
          CONFIG_PACKAGE_coreutils-base64=y
          CONFIG_PACKAGE_ip-full=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iptables-mod-tproxy=y
          CONFIG_PACKAGE_kcptun-client=y
          CONFIG_PACKAGE_kcptun-config=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_libbpf=y
          CONFIG_PACKAGE_libelf=y
          CONFIG_PACKAGE_libev=y
          CONFIG_PACKAGE_libmaxminddb=y
          CONFIG_PACKAGE_libmbedtls=y
          CONFIG_PACKAGE_libpcre=y
          CONFIG_PACKAGE_libsodium=y
          CONFIG_PACKAGE_libudns=y
          CONFIG_PACKAGE_lua-maxminddb=y
          CONFIG_PACKAGE_luasocket=y
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          # CONFIG_PACKAGE_luci-app-ddns is not set
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          # CONFIG_PACKAGE_luci-app-uugamebooster is not set
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          CONFIG_PACKAGE_luci-app-vssr=y
          CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Kcptun=y
          # CONFIG_PACKAGE_luci-app-wol is not set
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_shadowsocks-libev-config=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-check=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-redir=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-server=y
          CONFIG_PACKAGE_simple-obfs-client=y
          CONFIG_PACKAGE_trojan=y
          CONFIG_PACKAGE_wget-ssl=y
          CONFIG_PACKAGE_xray-core=y
          CONFIG_PACKAGE_xray-plugin=y
          CONFIG_PCRE_JIT_ENABLED=y
          # CONFIG_UnblockNeteaseMusic_Go is not set
          CONFIG_XRAY_CORE_COMPRESS_UPX=y
          CONFIG_boost-compile-visibility-hidden=y
          CONFIG_boost-runtime-shared=y
          CONFIG_boost-static-and-shared-libs=y
          CONFIG_boost-variant-release=y
          CONFIG_LIBCURL_COOKIES=y
          # CONFIG_LIBCURL_CRYPTO_AUTH is not set
          # CONFIG_LIBCURL_DICT is not set
          CONFIG_LIBCURL_FILE=y
          CONFIG_LIBCURL_FTP=y
          # CONFIG_LIBCURL_GNUTLS is not set
          # CONFIG_LIBCURL_GOPHER is not set
          CONFIG_LIBCURL_HTTP=y
          # CONFIG_LIBCURL_IMAP is not set
          # CONFIG_LIBCURL_LDAP is not set
          # CONFIG_LIBCURL_LIBCURL_OPTION is not set
          # CONFIG_LIBCURL_LIBIDN2 is not set
          # CONFIG_LIBCURL_MBEDTLS is not set
          # CONFIG_LIBCURL_NGHTTP2 is not set
          # CONFIG_LIBCURL_NOSSL is not set
          CONFIG_LIBCURL_NO_SMB="!"
          CONFIG_LIBCURL_OPENSSL=y
          # CONFIG_LIBCURL_POP3 is not set
          CONFIG_LIBCURL_PROXY=y
          # CONFIG_LIBCURL_RTSP is not set
          # CONFIG_LIBCURL_SMTP is not set
          # CONFIG_LIBCURL_SSH2 is not set
          # CONFIG_LIBCURL_TELNET is not set
          # CONFIG_LIBCURL_TFTP is not set
          # CONFIG_LIBCURL_THREADED_RESOLVER is not set
          # CONFIG_LIBCURL_TLS_SRP is not set
          # CONFIG_LIBCURL_UNIX_SOCKETS is not set
          # CONFIG_LIBCURL_VERBOSE is not set
          # CONFIG_LIBCURL_WOLFSSL is not set
          # CONFIG_LIBCURL_ZLIB is not set
          # CONFIG_LIBCURL_ZSTD is not set
          CONFIG_PACKAGE_UnblockNeteaseMusicGo=y
          CONFIG_PACKAGE_adbyby=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_etherwake=y
          CONFIG_PACKAGE_ip-tiny=y
          CONFIG_PACKAGE_iptables-mod-ipsec=y
          CONFIG_PACKAGE_kmod-crypto-acompress=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-deflate=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-echainiv=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          # CONFIG_PACKAGE_kmod-ip-vti is not set
          # CONFIG_PACKAGE_kmod-ip6-vti is not set
          CONFIG_PACKAGE_kmod-ipsec=y
          CONFIG_PACKAGE_kmod-ipsec4=y
          CONFIG_PACKAGE_kmod-ipsec6=y
          CONFIG_PACKAGE_kmod-ipt-ipsec=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-iptunnel6=y
          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
          CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
          CONFIG_PACKAGE_kmod-tun=y
          # CONFIG_PACKAGE_kmod-xfrm-interface is not set
          CONFIG_PACKAGE_libcurl=y
          CONFIG_PACKAGE_libgmp=y
          CONFIG_PACKAGE_libminiupnpc=y
          CONFIG_PACKAGE_libnatpmp=y
          CONFIG_PACKAGE_strongswan=y
          CONFIG_PACKAGE_strongswan-charon=y
          # CONFIG_PACKAGE_strongswan-charon-cmd is not set
          # CONFIG_PACKAGE_strongswan-default is not set
          # CONFIG_PACKAGE_strongswan-gencerts is not set
          CONFIG_PACKAGE_strongswan-ipsec=y
          # CONFIG_PACKAGE_strongswan-isakmp is not set
          # CONFIG_PACKAGE_strongswan-libnttfft is not set
          # CONFIG_PACKAGE_strongswan-libtls is not set
          CONFIG_PACKAGE_strongswan-minimal=y
          # CONFIG_PACKAGE_strongswan-mod-addrblock is not set
          CONFIG_PACKAGE_strongswan-mod-aes=y
          # CONFIG_PACKAGE_strongswan-mod-af-alg is not set
          # CONFIG_PACKAGE_strongswan-mod-agent is not set
          # CONFIG_PACKAGE_strongswan-mod-attr is not set
          # CONFIG_PACKAGE_strongswan-mod-attr-sql is not set
          # CONFIG_PACKAGE_strongswan-mod-bliss is not set
          # CONFIG_PACKAGE_strongswan-mod-blowfish is not set
          # CONFIG_PACKAGE_strongswan-mod-ccm is not set
          # CONFIG_PACKAGE_strongswan-mod-chapoly is not set
          # CONFIG_PACKAGE_strongswan-mod-cmac is not set
          # CONFIG_PACKAGE_strongswan-mod-connmark is not set
          # CONFIG_PACKAGE_strongswan-mod-constraints is not set
          # CONFIG_PACKAGE_strongswan-mod-coupling is not set
          # CONFIG_PACKAGE_strongswan-mod-ctr is not set
          # CONFIG_PACKAGE_strongswan-mod-curl is not set
          # CONFIG_PACKAGE_strongswan-mod-curve25519 is not set
          # CONFIG_PACKAGE_strongswan-mod-des is not set
          # CONFIG_PACKAGE_strongswan-mod-dhcp is not set
          # CONFIG_PACKAGE_strongswan-mod-dnskey is not set
          # CONFIG_PACKAGE_strongswan-mod-duplicheck is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-identity is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-md5 is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-mschapv2 is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-radius is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-tls is not set
          # CONFIG_PACKAGE_strongswan-mod-farp is not set
          # CONFIG_PACKAGE_strongswan-mod-fips-prf is not set
          # CONFIG_PACKAGE_strongswan-mod-forecast is not set
          # CONFIG_PACKAGE_strongswan-mod-gcm is not set
          # CONFIG_PACKAGE_strongswan-mod-gcrypt is not set
          CONFIG_PACKAGE_strongswan-mod-gmp=y
          # CONFIG_PACKAGE_strongswan-mod-gmpdh is not set
          # CONFIG_PACKAGE_strongswan-mod-ha is not set
          CONFIG_PACKAGE_strongswan-mod-hmac=y
          # CONFIG_PACKAGE_strongswan-mod-kernel-libipsec is not set
          CONFIG_PACKAGE_strongswan-mod-kernel-netlink=y
          # CONFIG_PACKAGE_strongswan-mod-ldap is not set
          # CONFIG_PACKAGE_strongswan-mod-led is not set
          # CONFIG_PACKAGE_strongswan-mod-load-tester is not set
          # CONFIG_PACKAGE_strongswan-mod-md4 is not set
          # CONFIG_PACKAGE_strongswan-mod-md5 is not set
          # CONFIG_PACKAGE_strongswan-mod-mgf1 is not set
          # CONFIG_PACKAGE_strongswan-mod-mysql is not set
          # CONFIG_PACKAGE_strongswan-mod-newhope is not set
          CONFIG_PACKAGE_strongswan-mod-nonce=y
          # CONFIG_PACKAGE_strongswan-mod-ntru is not set
          # CONFIG_PACKAGE_strongswan-mod-openssl is not set
          # CONFIG_PACKAGE_strongswan-mod-pem is not set
          # CONFIG_PACKAGE_strongswan-mod-pgp is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs1 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs11 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs12 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs7 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs8 is not set
          CONFIG_PACKAGE_strongswan-mod-pubkey=y
          CONFIG_PACKAGE_strongswan-mod-random=y
          # CONFIG_PACKAGE_strongswan-mod-rc2 is not set
          # CONFIG_PACKAGE_strongswan-mod-resolve is not set
          # CONFIG_PACKAGE_strongswan-mod-revocation is not set
          CONFIG_PACKAGE_strongswan-mod-sha1=y
          # CONFIG_PACKAGE_strongswan-mod-sha2 is not set
          # CONFIG_PACKAGE_strongswan-mod-sha3 is not set
          # CONFIG_PACKAGE_strongswan-mod-smp is not set
          CONFIG_PACKAGE_strongswan-mod-socket-default=y
          # CONFIG_PACKAGE_strongswan-mod-socket-dynamic is not set
          # CONFIG_PACKAGE_strongswan-mod-sql is not set
          # CONFIG_PACKAGE_strongswan-mod-sqlite is not set
          # CONFIG_PACKAGE_strongswan-mod-sshkey is not set
          CONFIG_PACKAGE_strongswan-mod-stroke=y
          # CONFIG_PACKAGE_strongswan-mod-test-vectors is not set
          # CONFIG_PACKAGE_strongswan-mod-uci is not set
          # CONFIG_PACKAGE_strongswan-mod-unity is not set
          CONFIG_PACKAGE_strongswan-mod-updown=y
          # CONFIG_PACKAGE_strongswan-mod-vici is not set
          # CONFIG_PACKAGE_strongswan-mod-whitelist is not set
          CONFIG_PACKAGE_strongswan-mod-x509=y
          # CONFIG_PACKAGE_strongswan-mod-xauth-eap is not set
          CONFIG_PACKAGE_strongswan-mod-xauth-generic=y
          CONFIG_PACKAGE_strongswan-mod-xcbc=y
          # CONFIG_PACKAGE_strongswan-pki is not set
          # CONFIG_PACKAGE_strongswan-scepclient is not set
          # CONFIG_PACKAGE_strongswan-swanctl is not set
          CONFIG_PACKAGE_uugamebooster=y
          CONFIG_PACKAGE_vsftpd-alt=y
          CONFIG_PACKAGE_wol=y
          # CONFIG_PACKAGE_xfrm is not set
          # CONFIG_PACKAGE_ykclient is not set
          CONFIG_PACKAGE_zerotier=y
          CONFIG_STRONGSWAN_ROUTING_TABLE="220"
          CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"
          CONFIG_VSFTPD_USE_UCI_SCRIPTS=y
          # CONFIG_ZEROTIER_ENABLE_DEBUG is not set
          # CONFIG_ZEROTIER_ENABLE_SELFTEST is not set
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
  

      - name: Upload release asset
        # if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
